[package]
name = "relibm"
version = "0.1.0"
authors = ["augustin <cheron.augustin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
libm = { path = "../.." }
libc = {version="0.2", default-features=false}