[package]
name = "hexf-cli"
version = "0.1.0"
authors = ["augustin <cheron.augustin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexf = "0.1.0"

